### ISSUE TITLE
Einige Endgeräte erhalten kein Netzwerkzugang (über WLAN)

### ISSUE THREAD

**Issue by oldwired** [toolbox-it/toolbox-netzwerk#71]
Es sieht so aus, als ob eine Verbindung zum AP noch gelingt, aber danach geht es nicht weiter.

**Comment by DO1JLR** [comment]
Am Sonntag hat das mit meinem Linux Laptop und Android Handy noch gut geklappt.

hast du mehr Details?

'Einige' Geräte klingt ja so wie, bei anderen Geräten tut es...

Eventuell ist die Verbindung von einem der APs aus zum Gateway gestört bzw. von Mäusen angeknabbert?

**Comment by rtt-mmk** [comment]
Das erklärt nicht, warum manche im ganzen Haus nicht mehr ins WLAN kamen. 

Vielleicht liegt/lag es am dhcp.tbbs.me? Die Konfiguration dieses Geräts würde ich mir sehr gerne mal ansehen...

**Comment by DO1JLR** [comment]
Mehr Informationen von wirklich betroffenen Geräten werden benötigt!

**Comment by rtt-mmk** [comment]
Gerne - Wenn du das wirklich möchtest, share ich gerne die Protokolle.

Und unterlasse es bitte, Inhalte von mir zu löschen, ohne, dass ich dir das erlaubt habe. Danke.

**Comment by rtt-mmk** [comment]
> Eventuell ist die Verbindung von einem der APs aus zum Gateway gestört bzw. von Mäusen angeknabbert?

Erklärt nicht, dass manche Mitglieder im ganzen Haus keinen Zugriff mehr auf das WLAN hatten. Und ihre Geräte nach der Einwahl ins WLAN einen disconnect erhielten.

**Comment by KnollMatthias** [comment]
Inzwischen ist klar, wieso es diese Probleme gab.

**Comment by DO1JLR** [comment]
ja, weil matt das nicht korrekt gemacht hat!
