### ISSUE TITLE
Dieses Repository ist der falschen Gruppe zugeordnet

### ISSUE THREAD

**Issue by oldwired** [toolbox-it/toolbox-netzwerk#75]
Dieses Repository gehört thematisch und inhaltlich zu https://github.com/ToolboxBodensee/   
Dort war es auch gestern noch zugeordnet. Auf welcher Grundlage wurde dieses Repository umgezogen?

**Comment by DO1JLR** [comment]
Aufgrund der Umstellung nach gitlab, der zu langsammen gitlab-UI, den fehlenden Berechtigungen im gitlab (halb-gefixt) und der "Alle commits auf github werden force-überschrieben"-Policy.

**Comment by maxbachmann** [comment]
? du hast auf gitlab die Berechtigungen um bei allen Infrastruktur und Streaming Dingen auf den Master branch zu pushen. Wenn da noch etwas fehlt, so wurde das zumindest mal nicht in Form eines issues eingebracht

**Comment by rtt-mmk** [comment]
also diese Repo gehört nicht in den Chaos-Bodensee - mit solchen Moves bekommt man in offiziellen Toolbox-Umgebungen auch sicher keine Berechtigungen mehr. Es macht nur unnötig viel Arbeit das wiederherstustellen - Herr zu Gott-Himmels...! Überleg mal kurz, was du bisher und damit jetzt so vollführst...

**Comment by rtt-mmk** [comment]
> ? du hast auf gitlab die Berechtigungen um bei allen Infrastruktur und Streaming Dingen auf den Master branch zu pushen. Wenn da noch etwas fehlt, so wurde das zumindest mal nicht in Form eines issues eingebracht
Also genauso die gleichen Rechte mit denen alle Mitlgieder außer dir schon seit jeher zurecht kommen müssen. Ich glaube, das ist ziemlich einleuchtend.

**Comment by maxbachmann** [comment]
@rtt-mmk bei Streaming und Infrastructure muss er das nicht mal, sondern kann eben auch auf den Master pushen.
Er kann nur nicht auf den master force pushen, oder repo settings ändern (also beispielsweise das repo löschen).

**Comment by xythobuz** [comment]
Also ich muss schon auch sagen, das klingt nach vorgeschobenen Gründen und in Wahrheit sind wir hier wirklich auf bestem Wege zu einem BOFH.

**Comment by maxbachmann** [comment]
ja ich finde auch https://github.com/chaos-bodensee/lektor-theme-landed sollte wieder in das Webseiten Repo zurück. 
1) wird das nur von der Toolbox genutzt (und auch nur auf der TB Webseite)
2) ist es stressig die Webseite jetzt and zwei Stellen zu verwalten und zum Beispiel Änderungen an dem theme nur noch manuell durch getestet werden kann
3) ist seitdem das rausbewegt wurde die Map auf der TB Webseite kaputt (hatte noch keine Zeit mir anzuschauen woran das genau liegt)

**Comment by rtt-mmk** [comment]
https://toolbox-bodensee.de/verein/Benutzungsordnung_Mitglieder.pdf
@DO1JLR  --> § 2.2. Ist nicht nur damit vollends nicht eingehalten.
Die anderen relevanten Ordnungen und Regelungen hast du sicher auch schon gesehen. Also halte dich bitte dran. Es wird sonst echt noch unschöner.

**Comment by DO1JLR** [comment]
@rtt-mmk hör auf mich zu belästigen!!!

**Comment by DO1JLR** [comment]
> ja ich finde auch https://github.com/chaos-bodensee/lektor-theme-landed sollte wieder in das Webseiten Repo zurück.
> 
>     1. wird das nur von der Toolbox genutzt (und auch nur auf der TB Webseite)
> 
>     2. ist es stressig die Webseite jetzt and zwei Stellen zu verwalten und zum Beispiel Änderungen an dem theme nur noch manuell durch getestet werden kann
> 
>     3. ist seitdem das rausbewegt wurde die Map auf der TB Webseite kaputt (hatte noch keine Zeit mir anzuschauen woran das genau liegt)

Zu erstens habe ich dir schon gesagt, was lage ist.

Aber ja, es verursacht mehr probleme als es aktuell löst. Zurück wäre mitunter sinvoll!

**Comment by maxbachmann** [comment]
ja das stimmt schon, macht den Punkt 1 aber ja nicht weniger wahr ;)

**Comment by DO1JLR** [comment]
> also diese Repo gehört nicht in den Chaos-Bodensee - mit solchen Moves bekommt man in offiziellen Toolbox-Umgebungen auch sicher keine Berechtigungen mehr. Es macht nur unnötig viel Arbeit das wiederherstustellen - Herr zu Gott-Himmels...! Überleg mal kurz, was du bisher und damit jetzt so vollführst...

Nein. Es gehört in ein Toolbox git in dem man arbeiten kann.

Wenn man allerdings durch "deine änderungen werden übrigens per force-push entfernt" davon mitbekommt, dass man jetzt gefälligst gitlab zu nutzen hat, was ihr hier übrigens nicht macht, dann bleiben da wenige möglichkeiten.

Bei Repos wie der Webseite wo man eine funktionierende CI braucht und die nun per gitlab realisiert wird oder schon wurde macht das ja sinn.

Bei Repos wie ansible, das nicht per CI deployed wird ist es unnötig.
Und wenn das dann ohne ankündigung, die die dort am aktivsten arbeitenden menschen erreicht (ja, mich), dann muss halt etwas getan werden um großen schaden zu verhindern.

Und gitlab...

Hab ich ausprobiert.
Ist irre langsam über die WebUI.

**Comment by DO1JLR** [comment]
> ja das stimmt schon, macht den Punkt 1 aber ja nicht weniger korrekt ;)

Es wird beim C3WOC noch nicht produktiv eingesetzt, weil noch nicht fertig gemerged. Aber trotzdem ist es für die Toolbox sinvoll das wieder zu vereinen.

Das "theme" Repo würde ich trotzdem nicht löschen sondern maximal archiviern oder erstmal so lassen und mit einem kommentar versehen!

**Comment by DO1JLR** [comment]
solved by creating toolbox-it
